

name: Gradle Publish to Maven Central

on:
  release:
    types:
        - created
        - edited

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
      SIGNING_KEY: ${{ secrets.GPG_SECRET }}
      SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Publish to Sonatype
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository